version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api_serve
    ports:
      - "8911:8911"
    volumes:
      - .:/home/node/app
    environment:
      - DATABASE_URL=file:./dev.db
      - SESSION_SECRET=9Svo/qMeEr/xn69l/SLD2mtB0z737dWpjRnMm9r/NQY=

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: web_serve
    ports:
      - "8910:8910"
    depends_on:
      - api
    environment:
      - API_PROXY_TARGET=http://api:8911
    volumes:
      - .:/home/node/app

  console:
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
      target: console
    volumes:
      - .:/home/node/app
    tmpfs:
      - /tmp
    command: "true"
    environment:
      - DATABASE_URL=file:./dev.db
