# fly.toml app configuration file generated for rsc-app on 2024-05-29T01:35:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rsc-app'
primary_region = 'lax'

[build]
  [build.args]
    NODE_VERSION = "20"

[deploy]
  release_command = '.fly/release.sh'

[env]
  MIGRATE_ON_BOOT = 'true'
  #PORT = '8910'
  REDWOOD_DISABLE_TELEMETRY = '1'

[[services]]
  http_checks = []
  internal_port = 8910
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = "80"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
