# fly.toml app configuration file generated for rsc-app on 2024-05-30T13:55:06-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rsc-app'
primary_region = 'lax'

[build]

[deploy]
  release_command = '.fly/release.sh'

[env]
  DATABASE_URL='file:./dev.db'
  MIGRATE_ON_BOOT = 'true'
  PORT = '8910'
  REDWOOD_DISABLE_TELEMETRY = '1'
  NODE_ENV = "production"
  API_PROXY_TARGET = "http://api:8911"

[mounts]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
